console-intro-message: true

join-event:
  enabled: true
  default-message: "&e&l[&f&l+&e&l] &c&l&n{player} &f&lhas joined!"
  default-sound: "NOTE_PLING"

quit-event:
  enabled: true
  default-message: "&e&l[&f&l-&e&l] &c&l&n{player} &f&lhas left!"
  default-sound: "NOTE_PLING"

sound-manager:
  enabled: true
  sound-mode: "everybody"
  volume: 1.0
  pitch: 0.0


custom-groups:
  '1':
    permission: "customjoinmessages.owner"
    join-message: "&c&lOWNER &c&l&n{player} &f&lhas joined!"
    quit-message: "NONE"
    join-sound: "NOTE_PLING"

  '2':
    permission: "customjoinmessages.admin"
    join-message: "&b&lADMIN &b&l&n{player} &f&lhas joined!"
    quit-message: "&b&lADMIN &b&l&n{player} &f&lhas left!"
    join-sound: "NOTE_PLING"

  '3':
    permission: "customjoinmessages.vip"
    join-message: "&e&lVIP &e&l&n{player} &f&lis now with us!"
    quit-message: "NONE"
    join-sound: "NOTE_PLING"
