name: CustomJoinMessages
version: 1.1
author: xDefcon
main: com.xdefcon.customjoinmessages.CustomJoinMessages
description: "Custom join/quit messages for your server."
commands:
  cjmreload:
    description: Reloads the plugin.